version: '3.7'

services:
  tfe:
    image: hashicorp/terraform-enterprise:v202404-2
    environment:
      - TFE_LICENSE=02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JLJDVS6SNKRSGUWLKNN2FSV2GNJNFGMBUJVCGY2SMK5KTETRSJV2E23KNPFHVIQTNJVDUS6K2NJATGSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJF4FURDENVGWU3DILJBTC22PIRSGQTCUIJUVUVCRORNFOWTJLJBTA52ONVCTGTTNKUZE26SBGFHG2RLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SRORGUIVLUJVKGIVKNIRRTMTL2JU3E22SVOVHEISJUJZVFCM2OPJITAV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJGBGFIQJRJRKEKM2WIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKKF2E2VCJORGXURSVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJIXITKUJF2E26SGKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZJGYY3OJJUFU3JZPFRFGSLTJFWVU42ZK5SHUSLKOA3WMWBQHUXDS2RTGBRXS6TOGI4HAVSYNBKUY2TPMVSU2RCMORIXKUSXOBDFAY2CKM4HEVKSK4ZGYRTFJBDDE4JSJJZFI5DFJVSHUZ3JKEYXKTTYMRBHUWLLJJKGKZ3WKQZUI6DEIFIDKN3COVBUUMLEIFVWGYJUMRLDAMZTHBIHO3KWNRQXMSSQGRYEU6CJJE4UINSVIZGFKYKWKBVGWV2KORRUINTQMFWDM32PMZDW4SZSPJIEWSSSNVDUQVRTMVNHO4KGMUVW6N3LF5ZSWQKUJZUFAWTHKMXUWVSZM4XUWK3MI5IHOTBXNJBHQSJXI5HWC2ZWKVQWSYKIN5SWWMCSKRXTOMSEKE6T2
      - TFE_HOSTNAME=tfe.local
      - TFE_POSTGRESQL_URL=postgres://tfe:tfe@postgres:5432/tfe?sslmode=disable
      - TFE_REDIS_URL=redis://redis:6379
      - TFE_STORAGE_PATH=/var/lib/tfe
    ports:
      - "8800:8800"
      - "8801:8801"
    volumes:
      - tfe-data:/var/lib/tfe

postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tfe
      POSTGRES_USER: tfe
      POSTGRES_PASSWORD: tfe
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  tfe-data:
  postgres-data:
  redis-data:
